# MTA Traffic Forecasting
Khyatee Desai & Justin Morgan
## Part 2: Data Cleaning
This notebook includes the data cleaning process

### Import Libraries

In [2]:
import pandas as pd
import numpy as np

### Import Data
Concatenate each data file into a Pandas dataframe

In [3]:
df = pd.read_csv("./data/turnstile_210313.txt")
df

,C/A,UNIT,SCP,STATION,LINENAME,DIVISION,DATE,TIME,DESC,ENTRIES,EXITS
0,A002,R051,02-00-00,59 ST,NQR456W,BMT,03/06/2021,03:00:00,REGULAR,7540642,2572027
1,A002,R051,02-00-00,59 ST,NQR456W,BMT,03/06/2021,07:00:00,REGULAR,7540645,2572030
2,A002,R051,02-00-00,59 ST,NQR456W,BMT,03/06/2021,11:00:00,REGULAR,7540676,2572093
3,A002,R051,02-00-00,59 ST,NQR456W,BMT,03/06/2021,15:00:00,REGULAR,7540764,2572128
4,A002,R051,02-00-00,59 ST,NQR456W,BMT,03/06/2021,19:00:00,REGULAR,7540904,2572160
...,...,...,...,...,...,...,...,...,...,...,...
209312,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,03/12/2021,04:00:00,REGULAR,5554,544
209313,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,03/12/2021,08:00:00,REGULAR,5554,544
209314,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,03/12/2021,12:00:00,REGULAR,5554,544
209315,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,03/12/2021,16:00:00,REGULAR,5554,544
209316,TRAM2,R469,00-05-01,RIT-ROOSEVELT,R,RIT,03/12/2021,20:00:00,REGULAR,5554,544